/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package system;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.HashSet;
import java.util.Map;
import java.util.Scanner;
import java.util.Set;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;

/**
 *
 * @author nisha
 */

public class LecturerRegistration extends javax.swing.JPanel {

    /**
     * Creates new form StudentRegistration
     */
    String KeyId;
    String KeyPass;
    String name;
    String ic;
    String dob;
    String gender;
    String number;
    String email;
    String school;
    String role;
    private JComboBox<String> School;
    private ArrayList<ConcreteLecturer> lecturers;
    
    
    
    public LecturerRegistration() {
        initComponents();

        School = new JComboBox<>();
        
        // Initialize student array
        lecturers = new ArrayList<>();
        
        populateSchoolComboBox(School);
        setupListeners();
        
        // Load existing data
        loadData();
        txtKeyId.setText(generateNextStudentID());
        
        
        
        //cboSchool.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGroup = new javax.swing.ButtonGroup();
        pnlMainLReg = new javax.swing.JLayeredPane();
        pnlLReg = new javax.swing.JPanel();
        lblLecturerTitle = new javax.swing.JLabel();
        lblLecturerKey = new javax.swing.JLabel();
        pnlLecturerKey = new javax.swing.JPanel();
        lblKeyId = new javax.swing.JLabel();
        txtKeyId = new javax.swing.JTextField();
        lblKeyPass = new javax.swing.JLabel();
        txtKeyPass = new javax.swing.JTextField();
        lblLecturerInfo = new javax.swing.JLabel();
        pnlLecturerDetails = new javax.swing.JPanel();
        lblName = new javax.swing.JLabel();
        lblICNo = new javax.swing.JLabel();
        lblDOB = new javax.swing.JLabel();
        lblGender = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        lblContactNo = new javax.swing.JLabel();
        txtIdNo = new javax.swing.JTextField();
        txtName = new javax.swing.JTextField();
        dataC = new com.toedter.calendar.JDateChooser();
        rdoMale = new javax.swing.JRadioButton();
        rdoFemale = new javax.swing.JRadioButton();
        txtEmail = new javax.swing.JTextField();
        txtContactNo = new javax.swing.JTextField();
        lblLecturerSchool = new javax.swing.JLabel();
        pnlLSchool = new javax.swing.JPanel();
        cboSchool = new javax.swing.JComboBox<>();
        lblSchool = new javax.swing.JLabel();
        btnClearS = new javax.swing.JButton();
        btnRegisterS = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        lblBack = new javax.swing.JLabel();
        lblBox = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(1075, 650));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlMainLReg.setPreferredSize(new java.awt.Dimension(1075, 650));
        pnlMainLReg.setLayout(new java.awt.CardLayout());

        pnlLReg.setBackground(new java.awt.Color(255, 255, 255));
        pnlLReg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblLecturerTitle.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        lblLecturerTitle.setForeground(new java.awt.Color(0, 0, 0));
        lblLecturerTitle.setText("Lecturer Registration");
        pnlLReg.add(lblLecturerTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 35, -1, -1));

        lblLecturerKey.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblLecturerKey.setForeground(new java.awt.Color(29, 62, 105));
        lblLecturerKey.setText("Lecturer Key");
        pnlLReg.add(lblLecturerKey, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, -1, -1));

        pnlLecturerKey.setBackground(new java.awt.Color(244, 244, 244));
        pnlLecturerKey.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(221, 218, 218), 1, true));
        pnlLecturerKey.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblKeyId.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblKeyId.setForeground(new java.awt.Color(0, 0, 0));
        lblKeyId.setText("Key ID : ");
        pnlLecturerKey.add(lblKeyId, new org.netbeans.lib.awtextra.AbsoluteConstraints(13, 15, 52, -1));

        txtKeyId.setBackground(new java.awt.Color(221, 218, 218));
        txtKeyId.setEnabled(false);
        pnlLecturerKey.add(txtKeyId, new org.netbeans.lib.awtextra.AbsoluteConstraints(73, 10, 237, -1));

        lblKeyPass.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblKeyPass.setForeground(new java.awt.Color(0, 0, 0));
        lblKeyPass.setText("Key Password : ");
        pnlLecturerKey.add(lblKeyPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 15, -1, -1));

        txtKeyPass.setBackground(new java.awt.Color(221, 218, 218));
        txtKeyPass.setForeground(new java.awt.Color(0, 0, 0));
        txtKeyPass.setEnabled(false);
        pnlLecturerKey.add(txtKeyPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 10, 237, -1));

        pnlLReg.add(pnlLecturerKey, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 1035, 50));

        lblLecturerInfo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblLecturerInfo.setForeground(new java.awt.Color(29, 62, 105));
        lblLecturerInfo.setText("Lecturer Personal Information");
        pnlLReg.add(lblLecturerInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, -1, -1));

        pnlLecturerDetails.setBackground(new java.awt.Color(244, 244, 244));
        pnlLecturerDetails.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(221, 218, 218), 1, true));
        pnlLecturerDetails.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblName.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblName.setForeground(new java.awt.Color(0, 0, 0));
        lblName.setText("Name : ");
        pnlLecturerDetails.add(lblName, new org.netbeans.lib.awtextra.AbsoluteConstraints(13, 15, 52, -1));

        lblICNo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblICNo.setForeground(new java.awt.Color(0, 0, 0));
        lblICNo.setText("IC No : ");
        pnlLecturerDetails.add(lblICNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(13, 50, 52, -1));

        lblDOB.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblDOB.setForeground(new java.awt.Color(0, 0, 0));
        lblDOB.setText("D.O.B : ");
        pnlLecturerDetails.add(lblDOB, new org.netbeans.lib.awtextra.AbsoluteConstraints(13, 90, 52, -1));

        lblGender.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblGender.setForeground(new java.awt.Color(0, 0, 0));
        lblGender.setText("Gender : ");
        pnlLecturerDetails.add(lblGender, new org.netbeans.lib.awtextra.AbsoluteConstraints(13, 125, 52, -1));

        lblEmail.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblEmail.setForeground(new java.awt.Color(0, 0, 0));
        lblEmail.setText("Email : ");
        pnlLecturerDetails.add(lblEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 50, 52, -1));

        lblContactNo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblContactNo.setForeground(new java.awt.Color(0, 0, 0));
        lblContactNo.setText("Contact No : ");
        pnlLecturerDetails.add(lblContactNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 95, 80, -1));

        txtIdNo.setBackground(new java.awt.Color(221, 218, 218));
        txtIdNo.setForeground(new java.awt.Color(0, 0, 0));
        pnlLecturerDetails.add(txtIdNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(73, 46, 237, -1));

        txtName.setBackground(new java.awt.Color(221, 218, 218));
        txtName.setForeground(new java.awt.Color(0, 0, 0));
        pnlLecturerDetails.add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(73, 10, 237, -1));

        dataC.setBackground(new java.awt.Color(255, 255, 255));
        dataC.setForeground(new java.awt.Color(0, 0, 0));
        dataC.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                dataCPropertyChange(evt);
            }
        });
        pnlLecturerDetails.add(dataC, new org.netbeans.lib.awtextra.AbsoluteConstraints(73, 80, 237, -1));

        btnGroup.add(rdoMale);
        rdoMale.setForeground(new java.awt.Color(0, 0, 0));
        rdoMale.setText("Male");
        pnlLecturerDetails.add(rdoMale, new org.netbeans.lib.awtextra.AbsoluteConstraints(75, 125, -1, -1));

        btnGroup.add(rdoFemale);
        rdoFemale.setForeground(new java.awt.Color(0, 0, 0));
        rdoFemale.setText("Female");
        pnlLecturerDetails.add(rdoFemale, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 125, -1, -1));

        txtEmail.setBackground(new java.awt.Color(221, 218, 218));
        txtEmail.setForeground(new java.awt.Color(0, 0, 0));
        pnlLecturerDetails.add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 45, 237, -1));

        txtContactNo.setBackground(new java.awt.Color(221, 218, 218));
        txtContactNo.setForeground(new java.awt.Color(0, 0, 0));
        txtContactNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtContactNoActionPerformed(evt);
            }
        });
        pnlLecturerDetails.add(txtContactNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 90, 237, -1));

        pnlLReg.add(pnlLecturerDetails, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 1035, 160));

        lblLecturerSchool.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblLecturerSchool.setForeground(new java.awt.Color(29, 62, 105));
        lblLecturerSchool.setText("Lecturer School");
        pnlLReg.add(lblLecturerSchool, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 370, -1, -1));

        pnlLSchool.setBackground(new java.awt.Color(244, 244, 244));
        pnlLSchool.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(221, 218, 218)));
        pnlLSchool.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cboSchool.setBackground(new java.awt.Color(204, 204, 204));
        cboSchool.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select" }));
        cboSchool.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 255)));
        pnlLSchool.add(cboSchool, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 180, -1));

        lblSchool.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblSchool.setForeground(new java.awt.Color(0, 0, 0));
        lblSchool.setText("School : ");
        pnlLSchool.add(lblSchool, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        pnlLReg.add(pnlLSchool, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 390, 1035, 130));

        btnClearS.setBackground(new java.awt.Color(102, 102, 102));
        btnClearS.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnClearS.setForeground(new java.awt.Color(255, 255, 255));
        btnClearS.setText("Clear");
        btnClearS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearSActionPerformed(evt);
            }
        });
        pnlLReg.add(btnClearS, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 570, -1, -1));

        btnRegisterS.setBackground(new java.awt.Color(51, 153, 255));
        btnRegisterS.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnRegisterS.setForeground(new java.awt.Color(255, 255, 255));
        btnRegisterS.setText("Register");
        btnRegisterS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisterSActionPerformed(evt);
            }
        });
        pnlLReg.add(btnRegisterS, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 570, -1, -1));

        btnCancel.setBackground(new java.awt.Color(255, 0, 0));
        btnCancel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnCancel.setForeground(new java.awt.Color(255, 255, 255));
        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });
        pnlLReg.add(btnCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 570, -1, -1));

        lblBack.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblBack.setForeground(new java.awt.Color(51, 153, 255));
        lblBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/system/img_icon/leftArrow.png"))); // NOI18N
        lblBack.setText("Lecturer Dashboard");
        lblBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblBackMouseClicked(evt);
            }
        });
        pnlLReg.add(lblBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 570, -1, -1));

        lblBox.setIcon(new javax.swing.ImageIcon(getClass().getResource("/system/img_icon/TransparentBox2.png"))); // NOI18N
        pnlLReg.add(lblBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1075, 650));

        pnlMainLReg.add(pnlLReg, "card2");

        add(pnlMainLReg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void populateSchoolComboBox(JComboBox<String> School) {
        Set<String> schoolH = new HashSet<>();
        BufferedReader reader = null;

        try {
            reader = new BufferedReader(new FileReader("course_list.txt"));
            String line;
            // Skip the header line
            reader.readLine();
            while ((line = reader.readLine()) != null) {
                String[] parts = line.split(",");
                if (parts.length >= 4) { // 
                    String school = parts[2].trim();
                    schoolH.add(school);

                }
            }
        } catch (IOException e) {
            e.printStackTrace(); // Handle file reading errors
        } finally {
            if (reader != null) {
                try {
                    reader.close();
                } catch (IOException e) {
                    e.printStackTrace();
                }
            }
        }
      
        

        // Update the combo box with unique study levels
        cboSchool.setModel(new DefaultComboBoxModel<>(schoolH.toArray(new String[0])));
    }
    
    private void setupListeners() {
        cboSchool.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                String selectedStudyLevel = (String) cboSchool.getSelectedItem();
                //cboSchool.setVisible(true);
               
            }
        });

     
    }



    private void txtContactNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtContactNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtContactNoActionPerformed

    private void btnClearSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearSActionPerformed
        txtKeyId.setText(generateNextStudentID());
        txtKeyPass.setText("");
        txtName.setText("");
        txtIdNo.setText("");
        dataC.setDate(null);
        btnGroup.clearSelection();
        txtContactNo.setText("");
        txtEmail.setText("");
        cboSchool.setSelectedIndex(-1);
    }//GEN-LAST:event_btnClearSActionPerformed

    private void dataCPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_dataCPropertyChange
         if ("date".equals(evt.getPropertyName())) {
                    Date selectedDate = (Date) evt.getNewValue();
                    if (selectedDate != null) {
                        //SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
                        SimpleDateFormat dateF = new SimpleDateFormat("ddMMYY");
                        String date = dateF.format(selectedDate);
                        
                        KeyPass = "LT@" + date;
                        
                        txtKeyPass.setText(KeyPass);
                        
                    }
                }
    }//GEN-LAST:event_dataCPropertyChange

    private void btnRegisterSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterSActionPerformed
        Date date = dataC.getDate();
        KeyId = txtKeyId.getText();
        KeyPass = txtKeyPass.getText();
        name = txtName.getText();
        ic = txtIdNo.getText();
       
        
        if(rdoMale.isSelected()){
            gender = "Male";
        }
        else if(rdoFemale.isSelected()){
            gender = "Female";
        }
        
        number = txtContactNo.getText();
        email = txtEmail.getText();
        school = cboSchool.getSelectedItem().toString();
        role = "-";

        
         // Check if a course with the same intake code already exists
        //boolean duplicateFound = false;
        boolean notCompletedForm = false;

        if (KeyId.isEmpty() || KeyPass.isEmpty() || name.isEmpty() || ic.isEmpty() || date == null || gender.isEmpty() || email.isEmpty() || number.isEmpty() || school.equals("Select") ) {
            notCompletedForm = true;
            JOptionPane.showMessageDialog(this, "Please complete the registration form");
        }

        dob = DateFormat.getDateInstance().format(date); // Convert to string

        //!duplicateFound && 
        if (!notCompletedForm) {
            ConcreteLecturer lecturer = new ConcreteLecturer(KeyId, KeyPass, name, ic, dob, gender, email, number, school, role);
            lecturers.add(lecturer);

            // Save data to file
            saveData();
            txtKeyId.setText(generateNextStudentID());
            txtKeyPass.setText("");
            txtName.setText("");
            txtIdNo.setText("");
            dataC.setDate(null);
            btnGroup.clearSelection();
            txtContactNo.setText("");
            txtEmail.setText("");
            cboSchool.setSelectedIndex(-1);
            
            
            
        } else {
            JOptionPane.showMessageDialog(this, "Duplicate intake code found. Please enter a unique intake code.");
        }
        
    }//GEN-LAST:event_btnRegisterSActionPerformed

    private void lblBackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBackMouseClicked
        LecturerDashboardA lectD = new LecturerDashboardA();
        pnlMainLReg.add(lectD);
        lectD.setVisible(true);
        pnlLReg.setVisible(false);
    }//GEN-LAST:event_lblBackMouseClicked

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        LecturerDashboardA lectD = new LecturerDashboardA();
        pnlMainLReg.add(lectD);
        lectD.setVisible(true);
        pnlLReg.setVisible(false);
    }//GEN-LAST:event_btnCancelActionPerformed


      private String generateNextStudentID() {
        try {
            
            Scanner scanner = new Scanner(new File("lecturer_list.txt"));
            
            Set<String> existingIDs = new HashSet<>();
            while (scanner.hasNextLine()) {
                String line = scanner.nextLine();
                
                String[] parts = line.split(",");
                String lecturerID = parts[0].trim();
                existingIDs.add(lecturerID);
            }
            scanner.close();

            
            int number = 1;
            while (existingIDs.contains("LT" + String.format("%03d", number))) {
                number++;
            }
            String nextStudentID = "LT" + String.format("%03d", number);
            return nextStudentID;
        } catch (FileNotFoundException e) {
            
            System.out.println("File not found: student.txt");
            e.printStackTrace();
        }
        return "L002"; 
    }
    private void loadData() {
        
        File file = new File("lecturer_list.txt");
        if (!file.exists()) {
            try {
                file.createNewFile(); // Create the file if it doesn't exist
            } catch (IOException e) {
                e.printStackTrace();
            }
        }
        try (BufferedReader reader = new BufferedReader(new FileReader(file))) {
            String line;
            while ((line = reader.readLine()) != null) {
                String[] parts = line.split(",");
                if (parts.length == 10) {
                    
                    ConcreteLecturer  lecturer = new ConcreteLecturer (parts[0], parts[1], parts[2], parts[3], parts[4], parts[5], parts[6], parts[7], parts[8], parts[9]);
                }
                
               
            }
        } catch (IOException e) {
            e.printStackTrace();
        }
    } 

    private void saveData() {
        try (BufferedWriter writer = new BufferedWriter(new FileWriter("lecturer_list.txt", true))) {
            for (Lecturer lecturer : lecturers) {
                boolean duplicate = false;
                try (BufferedReader reader = new BufferedReader(new FileReader("lecturer_list.txt"))) {
                    String line;
                    while ((line = reader.readLine()) != null) {
                        if (line.equals(lecturer.toString())) {
                            duplicate = true;
                            break;
                        }
                    }
                } catch (IOException e) {
                    e.printStackTrace();
                }
                if (!duplicate) {
                    writer.write(lecturer.toString());
                    writer.newLine();
                }
            }
        } catch (IOException e) {
            e.printStackTrace();
        }
    }

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnClearS;
    private javax.swing.ButtonGroup btnGroup;
    private javax.swing.JButton btnRegisterS;
    private javax.swing.JComboBox<String> cboSchool;
    private com.toedter.calendar.JDateChooser dataC;
    private javax.swing.JLabel lblBack;
    private javax.swing.JLabel lblBox;
    private javax.swing.JLabel lblContactNo;
    private javax.swing.JLabel lblDOB;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblGender;
    private javax.swing.JLabel lblICNo;
    private javax.swing.JLabel lblKeyId;
    private javax.swing.JLabel lblKeyPass;
    private javax.swing.JLabel lblLecturerInfo;
    private javax.swing.JLabel lblLecturerKey;
    private javax.swing.JLabel lblLecturerSchool;
    private javax.swing.JLabel lblLecturerTitle;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblSchool;
    private javax.swing.JPanel pnlLReg;
    private javax.swing.JPanel pnlLSchool;
    private javax.swing.JPanel pnlLecturerDetails;
    private javax.swing.JPanel pnlLecturerKey;
    private javax.swing.JLayeredPane pnlMainLReg;
    private javax.swing.JRadioButton rdoFemale;
    private javax.swing.JRadioButton rdoMale;
    private javax.swing.JTextField txtContactNo;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtIdNo;
    private javax.swing.JTextField txtKeyId;
    private javax.swing.JTextField txtKeyPass;
    private javax.swing.JTextField txtName;
    // End of variables declaration//GEN-END:variables
}
