/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package system;

import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author nisha
 */
public class LecturerPage extends javax.swing.JFrame {

    /**
     * Creates new form ProjectManager
     */
    LecturerDashboard dash = new LecturerDashboard();
    PresentationSchedule presentation = new PresentationSchedule();
    ReportEvaluationSupervisor reSupervisor = new ReportEvaluationSupervisor();
    ReportEvaluationSMarker reSMarker = new ReportEvaluationSMarker();
    ViewMarkerAccept view = new ViewMarkerAccept();
    RequestRole request = new RequestRole();
    LoginPage login = new LoginPage();
 
    public LecturerPage() {
        initComponents();

        pnlMain.add(dash);
        pnlMain.add(presentation );
        pnlMain.add(reSupervisor);
        pnlMain.add(reSMarker);
        pnlMain.add(view);
        pnlMain.add(request);
        dash.setVisible(false);
        presentation .setVisible(false);
        reSupervisor.setVisible(false);
        reSMarker.setVisible(false);
        view.setVisible(false);
        request.setVisible(false);
        
        lblId.setText(login.getUsername());
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlMenu = new javax.swing.JPanel();
        lblLogo = new javax.swing.JLabel();
        pnlRequestRole = new javax.swing.JPanel();
        lblRequestRole = new javax.swing.JLabel();
        pnlViewMarker = new javax.swing.JPanel();
        lblViewMarker = new javax.swing.JLabel();
        pnlReportEva = new javax.swing.JPanel();
        lblReportEva = new javax.swing.JLabel();
        pnlPresentation = new javax.swing.JPanel();
        lblPresentation = new javax.swing.JLabel();
        pnlDash = new javax.swing.JPanel();
        lblDash = new javax.swing.JLabel();
        lblSignOut = new javax.swing.JLabel();
        pnlProfile = new javax.swing.JPanel();
        lblMini = new javax.swing.JLabel();
        lblExit = new javax.swing.JLabel();
        lblAdminIcon = new javax.swing.JLabel();
        lblLect = new javax.swing.JLabel();
        lblId = new javax.swing.JLabel();
        pnlMain = new javax.swing.JLayeredPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlMenu.setBackground(new java.awt.Color(15, 30, 53));
        pnlMenu.setPreferredSize(new java.awt.Dimension(210, 750));
        pnlMenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/system/img_icon/logoT.png"))); // NOI18N
        pnlMenu.add(lblLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, -1, -1));

        pnlRequestRole.setBackground(new java.awt.Color(15, 30, 53));
        pnlRequestRole.setForeground(new java.awt.Color(204, 204, 204));
        pnlRequestRole.setPreferredSize(new java.awt.Dimension(210, 70));
        pnlRequestRole.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlRequestRoleMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlRequestRoleMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlRequestRoleMouseExited(evt);
            }
        });
        pnlRequestRole.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblRequestRole.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblRequestRole.setForeground(new java.awt.Color(153, 153, 153));
        lblRequestRole.setIcon(new javax.swing.ImageIcon(getClass().getResource("/system/img_icon/icons8_management_23px.png"))); // NOI18N
        lblRequestRole.setText("<html>Request Role</html>");
        lblRequestRole.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        lblRequestRole.setPreferredSize(new java.awt.Dimension(210, 80));
        pnlRequestRole.add(lblRequestRole, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 180, 40));

        pnlMenu.add(pnlRequestRole, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 390, 210, 60));

        pnlViewMarker.setBackground(new java.awt.Color(15, 30, 53));
        pnlViewMarker.setForeground(new java.awt.Color(204, 204, 204));
        pnlViewMarker.setPreferredSize(new java.awt.Dimension(210, 70));
        pnlViewMarker.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlViewMarkerMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlViewMarkerMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlViewMarkerMouseExited(evt);
            }
        });
        pnlViewMarker.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblViewMarker.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblViewMarker.setForeground(new java.awt.Color(153, 153, 153));
        lblViewMarker.setIcon(new javax.swing.ImageIcon(getClass().getResource("/system/img_icon/icons8_view_23px.png"))); // NOI18N
        lblViewMarker.setText("<html>View Marker Acceptance</html>");
        lblViewMarker.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        lblViewMarker.setPreferredSize(new java.awt.Dimension(210, 80));
        pnlViewMarker.add(lblViewMarker, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 180, 40));

        pnlMenu.add(pnlViewMarker, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 330, 210, 60));

        pnlReportEva.setBackground(new java.awt.Color(15, 30, 53));
        pnlReportEva.setForeground(new java.awt.Color(204, 204, 204));
        pnlReportEva.setPreferredSize(new java.awt.Dimension(210, 70));
        pnlReportEva.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlReportEvaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlReportEvaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlReportEvaMouseExited(evt);
            }
        });
        pnlReportEva.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblReportEva.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblReportEva.setForeground(new java.awt.Color(153, 153, 153));
        lblReportEva.setIcon(new javax.swing.ImageIcon(getClass().getResource("/system/img_icon/icons8_edit_graph_report_23px.png"))); // NOI18N
        lblReportEva.setText("<html>Report Evaluation</html>");
        lblReportEva.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        lblReportEva.setPreferredSize(new java.awt.Dimension(210, 80));
        pnlReportEva.add(lblReportEva, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 180, 40));

        pnlMenu.add(pnlReportEva, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 210, 60));

        pnlPresentation.setBackground(new java.awt.Color(15, 30, 53));
        pnlPresentation.setForeground(new java.awt.Color(204, 204, 204));
        pnlPresentation.setPreferredSize(new java.awt.Dimension(210, 70));
        pnlPresentation.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlPresentationMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlPresentationMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlPresentationMouseExited(evt);
            }
        });
        pnlPresentation.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblPresentation.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblPresentation.setForeground(new java.awt.Color(153, 153, 153));
        lblPresentation.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblPresentation.setIcon(new javax.swing.ImageIcon(getClass().getResource("/system/img_icon/icons8_schedule_20px.png"))); // NOI18N
        lblPresentation.setText("Presentation Schedule");
        lblPresentation.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        lblPresentation.setPreferredSize(new java.awt.Dimension(210, 80));
        pnlPresentation.add(lblPresentation, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 180, 30));

        pnlMenu.add(pnlPresentation, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, 210, 50));

        pnlDash.setBackground(new java.awt.Color(15, 30, 53));
        pnlDash.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlDashMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlDashMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlDashMouseExited(evt);
            }
        });
        pnlDash.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblDash.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblDash.setForeground(new java.awt.Color(153, 153, 153));
        lblDash.setIcon(new javax.swing.ImageIcon(getClass().getResource("/system/img_icon/dashboard (1).png"))); // NOI18N
        lblDash.setText("Dashboard");
        lblDash.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        lblDash.setIconTextGap(15);
        lblDash.setPreferredSize(new java.awt.Dimension(210, 80));
        pnlDash.add(lblDash, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 150, 30));

        pnlMenu.add(pnlDash, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 210, 50));

        lblSignOut.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblSignOut.setForeground(new java.awt.Color(153, 153, 153));
        lblSignOut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/system/img_icon/iconLogOut.png"))); // NOI18N
        lblSignOut.setText("LogOut");
        lblSignOut.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        lblSignOut.setPreferredSize(new java.awt.Dimension(210, 80));
        lblSignOut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblSignOutMouseClicked(evt);
            }
        });
        pnlMenu.add(lblSignOut, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 640, 180, 40));

        getContentPane().add(pnlMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 210, 710));

        pnlProfile.setBackground(new java.awt.Color(255, 255, 255));
        pnlProfile.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED, java.awt.Color.lightGray, java.awt.Color.lightGray, java.awt.Color.lightGray, java.awt.Color.lightGray));
        pnlProfile.setPreferredSize(new java.awt.Dimension(1120, 60));
        pnlProfile.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblMini.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblMini.setForeground(new java.awt.Color(153, 153, 153));
        lblMini.setText("-");
        lblMini.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblMiniMouseClicked(evt);
            }
        });
        pnlProfile.add(lblMini, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 15, -1, -1));

        lblExit.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblExit.setForeground(new java.awt.Color(153, 153, 153));
        lblExit.setText(" X ");
        lblExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblExitMouseClicked(evt);
            }
        });
        pnlProfile.add(lblExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 15, -1, -1));

        lblAdminIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/system/img_icon/iconLecturer.png"))); // NOI18N
        pnlProfile.add(lblAdminIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 15, -1, -1));

        lblLect.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        lblLect.setForeground(new java.awt.Color(0, 0, 0));
        lblLect.setText("Lecturer");
        pnlProfile.add(lblLect, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 20, -1, -1));

        lblId.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblId.setForeground(new java.awt.Color(0, 0, 204));
        pnlProfile.add(lblId, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 40, -1, -1));

        getContentPane().add(pnlProfile, new org.netbeans.lib.awtextra.AbsoluteConstraints(165, -10, 1120, 70));

        pnlMain.setBackground(new java.awt.Color(255, 255, 255));
        pnlMain.setMinimumSize(new java.awt.Dimension(1075, 640));
        pnlMain.setPreferredSize(new java.awt.Dimension(1075, 650));
        pnlMain.setLayout(new java.awt.CardLayout());
        getContentPane().add(pnlMain, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 60, 1075, 650));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void pnlViewMarkerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlViewMarkerMouseClicked
        dash.setVisible(false);
        presentation .setVisible(false);
        reSupervisor.setVisible(false);
        reSMarker.setVisible(false);
        view.setVisible(true);
        request.setVisible(false);
        lblViewMarker.setForeground(new java.awt.Color(56, 182, 255));
        lblDash.setForeground(new java.awt.Color(153,153,153));
        lblReportEva.setForeground(new java.awt.Color(153,153,153));
        lblPresentation.setForeground(new java.awt.Color(153,153,153));
        lblRequestRole.setForeground(new java.awt.Color(153,153,153));
    }//GEN-LAST:event_pnlViewMarkerMouseClicked

    private void pnlViewMarkerMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlViewMarkerMouseEntered
        pnlViewMarker.setBackground(Color.white);
    }//GEN-LAST:event_pnlViewMarkerMouseEntered

    private void pnlViewMarkerMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlViewMarkerMouseExited
        pnlViewMarker.setBackground(new java.awt.Color(15,30,55));
    }//GEN-LAST:event_pnlViewMarkerMouseExited

    private void pnlReportEvaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlReportEvaMouseClicked
        dash.setVisible(false);
        presentation .setVisible(false);
        if(login.getRole().equals("Supervisor")){
            reSupervisor.setVisible(true);
        }else{
            reSMarker.setVisible(true);
        }
        view.setVisible(false);
        request.setVisible(false);
        lblReportEva.setForeground(new java.awt.Color(56, 182, 255));
        lblDash.setForeground(new java.awt.Color(153,153,153));
        lblPresentation.setForeground(new java.awt.Color(153,153,153));
        lblViewMarker.setForeground(new java.awt.Color(153,153,153));
        lblRequestRole.setForeground(new java.awt.Color(153,153,153));
    }//GEN-LAST:event_pnlReportEvaMouseClicked

    private void pnlReportEvaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlReportEvaMouseEntered
        pnlReportEva.setBackground(Color.white);
    }//GEN-LAST:event_pnlReportEvaMouseEntered

    private void pnlReportEvaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlReportEvaMouseExited
        pnlReportEva.setBackground(new java.awt.Color(15,30,55));
    }//GEN-LAST:event_pnlReportEvaMouseExited

    private void pnlPresentationMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlPresentationMouseClicked
        pnlPresentation.setBackground(Color.white);
        dash.setVisible(false);
        presentation .setVisible(true);
        reSupervisor.setVisible(false);
        reSMarker.setVisible(false);
        view.setVisible(false);
        request.setVisible(false);
        lblPresentation.setForeground(new java.awt.Color(56, 182, 255));
        lblDash.setForeground(new java.awt.Color(153,153,153));
        lblReportEva.setForeground(new java.awt.Color(153,153,153));
        lblViewMarker.setForeground(new java.awt.Color(153,153,153));
        lblRequestRole.setForeground(new java.awt.Color(153,153,153));
    }//GEN-LAST:event_pnlPresentationMouseClicked

    private void pnlPresentationMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlPresentationMouseEntered
        pnlPresentation.setBackground(Color.white);
    }//GEN-LAST:event_pnlPresentationMouseEntered

    private void pnlPresentationMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlPresentationMouseExited
        pnlPresentation.setBackground(new java.awt.Color(15,30,55));
    }//GEN-LAST:event_pnlPresentationMouseExited

    private void pnlDashMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlDashMouseClicked
        dash.setVisible(true);
        presentation .setVisible(false);
        reSupervisor.setVisible(false);
        reSMarker.setVisible(false);
        view.setVisible(false);
        request.setVisible(false);
        lblDash.setForeground(new java.awt.Color(56, 182, 255));
        lblPresentation.setForeground(new java.awt.Color(153,153,153));
        lblReportEva.setForeground(new java.awt.Color(153,153,153));
        lblViewMarker.setForeground(new java.awt.Color(153,153,153));
        lblRequestRole.setForeground(new java.awt.Color(153,153,153));

    }//GEN-LAST:event_pnlDashMouseClicked

    private void pnlDashMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlDashMouseEntered
        pnlDash.setBackground(Color.white);
        //lblDash.setForeground(Color.BLACK);
    }//GEN-LAST:event_pnlDashMouseEntered

    private void pnlDashMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlDashMouseExited
        pnlDash.setBackground(new java.awt.Color(15,30,55));
    }//GEN-LAST:event_pnlDashMouseExited

    private void lblMiniMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMiniMouseClicked
        this.setExtendedState(Admin.ICONIFIED);
    }//GEN-LAST:event_lblMiniMouseClicked

    private void lblExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblExitMouseClicked
        System.exit(0);
    }//GEN-LAST:event_lblExitMouseClicked

    private void pnlRequestRoleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlRequestRoleMouseClicked
        dash.setVisible(false);
        presentation .setVisible(false);
        reSupervisor.setVisible(false);
        reSMarker.setVisible(false);
        view.setVisible(false);
        request.setVisible(true);
        lblRequestRole.setForeground(new java.awt.Color(56, 182, 255));
        lblPresentation.setForeground(new java.awt.Color(153,153,153));
        lblReportEva.setForeground(new java.awt.Color(153,153,153));
        lblViewMarker.setForeground(new java.awt.Color(153,153,153));
        lblDash.setForeground(new java.awt.Color(153,153,153));
    }//GEN-LAST:event_pnlRequestRoleMouseClicked

    private void pnlRequestRoleMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlRequestRoleMouseEntered
        pnlRequestRole.setBackground(Color.white);
    }//GEN-LAST:event_pnlRequestRoleMouseEntered

    private void pnlRequestRoleMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlRequestRoleMouseExited
        pnlRequestRole.setBackground(new java.awt.Color(15,30,55));
    }//GEN-LAST:event_pnlRequestRoleMouseExited

    private void lblSignOutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSignOutMouseClicked
        LoginPage login = new LoginPage();
        login.show();
        dispose();// closing our current Menu
        JOptionPane.showMessageDialog(null, "Logout successful");
    }//GEN-LAST:event_lblSignOutMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LecturerPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LecturerPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LecturerPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LecturerPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LecturerPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblAdminIcon;
    private javax.swing.JLabel lblDash;
    private javax.swing.JLabel lblExit;
    private javax.swing.JLabel lblId;
    private javax.swing.JLabel lblLect;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblMini;
    private javax.swing.JLabel lblPresentation;
    private javax.swing.JLabel lblReportEva;
    private javax.swing.JLabel lblRequestRole;
    private javax.swing.JLabel lblSignOut;
    private javax.swing.JLabel lblViewMarker;
    private javax.swing.JPanel pnlDash;
    private javax.swing.JLayeredPane pnlMain;
    private javax.swing.JPanel pnlMenu;
    private javax.swing.JPanel pnlPresentation;
    private javax.swing.JPanel pnlProfile;
    private javax.swing.JPanel pnlReportEva;
    private javax.swing.JPanel pnlRequestRole;
    private javax.swing.JPanel pnlViewMarker;
    // End of variables declaration//GEN-END:variables
}
