/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package system;

import java.awt.Color;
import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;
import java.text.SimpleDateFormat;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.Date;
import javax.swing.border.Border;
import javax.swing.border.LineBorder;

/**
 *
 * @author nisha
 */
public class LecturerDashboardA extends javax.swing.JPanel {

    /**
     * Creates new form StudentDashboard
     */
    LecturerRegistration lecturerR = new LecturerRegistration();
    LecturerEditDelete modify = new LecturerEditDelete();
    LecturerRegistrationList list = new LecturerRegistrationList();
    Border lineBorder = new LineBorder(Color.BLUE, 2, true);
    Border lineBorder2 = new LineBorder(Color.WHITE, 2, true);
    
    public LecturerDashboardA() {
        initComponents();
        pnlMainDash.add(lecturerR);
        pnlMainDash.add(modify);
        pnlMainDash.add(list);
        lecturerR.setVisible(false);
        modify.setVisible(false);
        list.setVisible(false);
        
        Date currentDate = new Date();
        
        // Create SimpleDateFormat instance with the desired format
        SimpleDateFormat sdf = new SimpleDateFormat("MMMM d, EEEE");
        
        // Format the current date
        String formattedDate = sdf.format(currentDate); 
        lblDate.setText(formattedDate.toString());
        
        // Count records and set label text
        int totalRecords = countRecords();
        lblTotalL.setText(String.valueOf(totalRecords));
        
       
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlMainDash = new javax.swing.JLayeredPane();
        pnlDashL = new javax.swing.JPanel();
        lblLecturerDTitle = new javax.swing.JLabel();
        lblDate = new javax.swing.JLabel();
        lblLTitle = new javax.swing.JLabel();
        lblMsg = new javax.swing.JLabel();
        lblBgDashL = new javax.swing.JLabel();
        lblModifyL = new javax.swing.JLabel();
        lblListL = new javax.swing.JLabel();
        lblRegL = new javax.swing.JLabel();
        lblManage = new javax.swing.JLabel();
        lblTotalL = new javax.swing.JLabel();
        lblTTotal = new javax.swing.JLabel();
        lblTL = new javax.swing.JLabel();
        lblBgTotal = new javax.swing.JLabel();
        lblBox = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(1075, 650));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlMainDash.setLayout(new java.awt.CardLayout());

        pnlDashL.setBackground(new java.awt.Color(255, 255, 255));
        pnlDashL.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblLecturerDTitle.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        lblLecturerDTitle.setText("Dashboard Lecturer");
        pnlDashL.add(lblLecturerDTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 35, -1, -1));

        lblDate.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblDate.setForeground(new java.awt.Color(255, 255, 255));
        lblDate.setText("jLabel1");
        pnlDashL.add(lblDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 130, 190, -1));

        lblLTitle.setBackground(new java.awt.Color(255, 255, 255));
        lblLTitle.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lblLTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblLTitle.setText("Lecturer Management ");
        pnlDashL.add(lblLTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 160, -1, -1));

        lblMsg.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblMsg.setForeground(new java.awt.Color(255, 255, 255));
        lblMsg.setText("Welcome back, Admin!");
        pnlDashL.add(lblMsg, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 220, -1, -1));

        lblBgDashL.setIcon(new javax.swing.ImageIcon(getClass().getResource("/system/img_icon/bgDashL.png"))); // NOI18N
        pnlDashL.add(lblBgDashL, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 690, 180));

        lblModifyL.setBackground(new java.awt.Color(255, 255, 255));
        lblModifyL.setIcon(new javax.swing.ImageIcon(getClass().getResource("/system/img_icon/bgModify.png"))); // NOI18N
        lblModifyL.setOpaque(true);
        lblModifyL.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblModifyLMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblModifyLMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblModifyLMouseExited(evt);
            }
        });
        pnlDashL.add(lblModifyL, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 350, -1, -1));

        lblListL.setBackground(new java.awt.Color(255, 255, 255));
        lblListL.setIcon(new javax.swing.ImageIcon(getClass().getResource("/system/img_icon/bgDList.png"))); // NOI18N
        lblListL.setOpaque(true);
        lblListL.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblListLMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblListLMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblListLMouseExited(evt);
            }
        });
        pnlDashL.add(lblListL, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 350, -1, -1));

        lblRegL.setBackground(new java.awt.Color(255, 255, 255));
        lblRegL.setIcon(new javax.swing.ImageIcon(getClass().getResource("/system/img_icon/bgDRegL.png"))); // NOI18N
        lblRegL.setOpaque(true);
        lblRegL.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblRegLMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblRegLMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblRegLMouseExited(evt);
            }
        });
        pnlDashL.add(lblRegL, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 350, -1, -1));

        lblManage.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        lblManage.setText("Manage");
        pnlDashL.add(lblManage, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 290, -1, -1));

        lblTotalL.setFont(new java.awt.Font("Segoe UI", 1, 60)); // NOI18N
        lblTotalL.setForeground(new java.awt.Color(255, 255, 255));
        lblTotalL.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTotalL.setText("0");
        pnlDashL.add(lblTotalL, new org.netbeans.lib.awtextra.AbsoluteConstraints(929, 155, 80, -1));

        lblTTotal.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lblTTotal.setForeground(new java.awt.Color(255, 255, 255));
        lblTTotal.setText("Total ");
        pnlDashL.add(lblTTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 130, -1, -1));

        lblTL.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblTL.setForeground(new java.awt.Color(255, 255, 255));
        lblTL.setText("Lecturer");
        pnlDashL.add(lblTL, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 230, -1, -1));

        lblBgTotal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/system/img_icon/bgTotal.png"))); // NOI18N
        pnlDashL.add(lblBgTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 100, 280, 180));

        lblBox.setIcon(new javax.swing.ImageIcon(getClass().getResource("/system/img_icon/TransparentBox2.png"))); // NOI18N
        pnlDashL.add(lblBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1075, 650));

        pnlMainDash.add(pnlDashL, "card2");

        add(pnlMainDash, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1075, 650));
    }// </editor-fold>//GEN-END:initComponents

    private void lblRegLMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblRegLMouseEntered

        lblRegL.setBorder(lineBorder); // Set the border to the label
        
    }//GEN-LAST:event_lblRegLMouseEntered

    private void lblRegLMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblRegLMouseClicked

        lecturerR.setVisible(true);
        pnlDashL.setVisible(false);
        modify.setVisible(false);
        list.setVisible(false);
    }//GEN-LAST:event_lblRegLMouseClicked

    private void lblRegLMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblRegLMouseExited
        lblRegL.setBackground(Color.white);
        lblRegL.setBorder(lineBorder2); // Set the border to the label
    }//GEN-LAST:event_lblRegLMouseExited

    private void lblListLMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblListLMouseEntered

        lblListL.setBorder(lineBorder); // Set the border to the label
    }//GEN-LAST:event_lblListLMouseEntered

    private void lblListLMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblListLMouseExited
        lblListL.setBorder(lineBorder2); // Set the border to the label
    }//GEN-LAST:event_lblListLMouseExited

    private void lblListLMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblListLMouseClicked
        lecturerR.setVisible(false);
        pnlDashL.setVisible(false);
        modify.setVisible(false);
        list.setVisible(true);
    }//GEN-LAST:event_lblListLMouseClicked

    private void lblModifyLMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblModifyLMouseEntered
        lblModifyL.setBorder(lineBorder); // Set the border to the label
    }//GEN-LAST:event_lblModifyLMouseEntered

    private void lblModifyLMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblModifyLMouseExited
        lblModifyL.setBorder(lineBorder2); // Set the border to the label
    }//GEN-LAST:event_lblModifyLMouseExited

    private void lblModifyLMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblModifyLMouseClicked
        lecturerR.setVisible(false);
        pnlDashL.setVisible(false);
        modify.setVisible(true);
        list.setVisible(false);
    }//GEN-LAST:event_lblModifyLMouseClicked

    //Function for count number of student registered
    public int countRecords() {
    int count = 0;
    try (BufferedReader reader = new BufferedReader(new FileReader("lecturer_list.txt"))) {
        while (reader.readLine() != null) {
            count++;
        }
    } catch (IOException e) {
        e.printStackTrace();
    }
    return count;
}


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblBgDashL;
    private javax.swing.JLabel lblBgTotal;
    private javax.swing.JLabel lblBox;
    private javax.swing.JLabel lblDate;
    private javax.swing.JLabel lblLTitle;
    private javax.swing.JLabel lblLecturerDTitle;
    private javax.swing.JLabel lblListL;
    private javax.swing.JLabel lblManage;
    private javax.swing.JLabel lblModifyL;
    private javax.swing.JLabel lblMsg;
    private javax.swing.JLabel lblRegL;
    private javax.swing.JLabel lblTL;
    private javax.swing.JLabel lblTTotal;
    private javax.swing.JLabel lblTotalL;
    private javax.swing.JPanel pnlDashL;
    private javax.swing.JLayeredPane pnlMainDash;
    // End of variables declaration//GEN-END:variables
}
