/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package system;

import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author nisha
 */
public class StudentPage extends javax.swing.JFrame {

    /**
     * Creates new form ProjectManager
     */

    ReportSubmission submit = new ReportSubmission();
    RequestPresentationDate present = new RequestPresentationDate();
    CheckResult result = new CheckResult();

    LoginPage login = new LoginPage();
 
    public StudentPage() {
        initComponents();


        pnlMain.add(submit);
        pnlMain.add( present);
        pnlMain.add(result);

        submit .setVisible(false);

        lblId.setText(login.getUsername());
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlMenu = new javax.swing.JPanel();
        lblLogo = new javax.swing.JLabel();
        pnlCheckResult = new javax.swing.JPanel();
        lblCheckResult = new javax.swing.JLabel();
        pnlReqPresentation = new javax.swing.JPanel();
        lblReqPresentation = new javax.swing.JLabel();
        pnlReportSub = new javax.swing.JPanel();
        lblReportSub = new javax.swing.JLabel();
        lblSignOut = new javax.swing.JLabel();
        pnlProfile = new javax.swing.JPanel();
        lblMini = new javax.swing.JLabel();
        lblExit = new javax.swing.JLabel();
        lblAdminIcon = new javax.swing.JLabel();
        lblStud = new javax.swing.JLabel();
        lblId = new javax.swing.JLabel();
        pnlMain = new javax.swing.JLayeredPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlMenu.setBackground(new java.awt.Color(15, 30, 53));
        pnlMenu.setPreferredSize(new java.awt.Dimension(210, 750));
        pnlMenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/system/img_icon/logoT.png"))); // NOI18N
        pnlMenu.add(lblLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, -1, -1));

        pnlCheckResult.setBackground(new java.awt.Color(15, 30, 53));
        pnlCheckResult.setForeground(new java.awt.Color(204, 204, 204));
        pnlCheckResult.setPreferredSize(new java.awt.Dimension(210, 70));
        pnlCheckResult.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlCheckResultMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlCheckResultMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlCheckResultMouseExited(evt);
            }
        });
        pnlCheckResult.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblCheckResult.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblCheckResult.setForeground(new java.awt.Color(153, 153, 153));
        lblCheckResult.setIcon(new javax.swing.ImageIcon(getClass().getResource("/system/img_icon/icons8_view_23px.png"))); // NOI18N
        lblCheckResult.setText("<html>Result</html>");
        lblCheckResult.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        lblCheckResult.setPreferredSize(new java.awt.Dimension(210, 80));
        pnlCheckResult.add(lblCheckResult, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 10, 180, 30));

        pnlMenu.add(pnlCheckResult, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 330, 210, 60));

        pnlReqPresentation.setBackground(new java.awt.Color(15, 30, 53));
        pnlReqPresentation.setForeground(new java.awt.Color(204, 204, 204));
        pnlReqPresentation.setPreferredSize(new java.awt.Dimension(210, 70));
        pnlReqPresentation.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlReqPresentationMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlReqPresentationMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlReqPresentationMouseExited(evt);
            }
        });
        pnlReqPresentation.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblReqPresentation.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblReqPresentation.setForeground(new java.awt.Color(153, 153, 153));
        lblReqPresentation.setIcon(new javax.swing.ImageIcon(getClass().getResource("/system/img_icon/icons8_schedule_20px.png"))); // NOI18N
        lblReqPresentation.setText("<html>Request Presentation Date</html>");
        lblReqPresentation.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        lblReqPresentation.setPreferredSize(new java.awt.Dimension(210, 80));
        pnlReqPresentation.add(lblReqPresentation, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 10, 180, 40));

        pnlMenu.add(pnlReqPresentation, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 210, 60));

        pnlReportSub.setBackground(new java.awt.Color(15, 30, 53));
        pnlReportSub.setForeground(new java.awt.Color(204, 204, 204));
        pnlReportSub.setPreferredSize(new java.awt.Dimension(210, 70));
        pnlReportSub.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlReportSubMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlReportSubMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlReportSubMouseExited(evt);
            }
        });
        pnlReportSub.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblReportSub.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblReportSub.setForeground(new java.awt.Color(153, 153, 153));
        lblReportSub.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblReportSub.setIcon(new javax.swing.ImageIcon(getClass().getResource("/system/img_icon/icons8_submit_document_23px.png"))); // NOI18N
        lblReportSub.setText("Report Submission");
        lblReportSub.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        lblReportSub.setPreferredSize(new java.awt.Dimension(210, 80));
        pnlReportSub.add(lblReportSub, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 10, 180, 30));

        pnlMenu.add(pnlReportSub, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, 210, 50));

        lblSignOut.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblSignOut.setForeground(new java.awt.Color(153, 153, 153));
        lblSignOut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/system/img_icon/iconLogOut.png"))); // NOI18N
        lblSignOut.setText("LogOut");
        lblSignOut.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        lblSignOut.setPreferredSize(new java.awt.Dimension(210, 80));
        lblSignOut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblSignOutMouseClicked(evt);
            }
        });
        pnlMenu.add(lblSignOut, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 640, 180, 40));

        getContentPane().add(pnlMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 210, 710));

        pnlProfile.setBackground(new java.awt.Color(255, 255, 255));
        pnlProfile.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED, java.awt.Color.lightGray, java.awt.Color.lightGray, java.awt.Color.lightGray, java.awt.Color.lightGray));
        pnlProfile.setPreferredSize(new java.awt.Dimension(1120, 60));
        pnlProfile.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblMini.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblMini.setForeground(new java.awt.Color(153, 153, 153));
        lblMini.setText("-");
        lblMini.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblMiniMouseClicked(evt);
            }
        });
        pnlProfile.add(lblMini, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 15, -1, -1));

        lblExit.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblExit.setForeground(new java.awt.Color(153, 153, 153));
        lblExit.setText(" X ");
        lblExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblExitMouseClicked(evt);
            }
        });
        pnlProfile.add(lblExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 15, -1, -1));

        lblAdminIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/system/img_icon/icons8_student_male_50px_2.png"))); // NOI18N
        pnlProfile.add(lblAdminIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 15, -1, -1));

        lblStud.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        lblStud.setForeground(new java.awt.Color(0, 0, 0));
        lblStud.setText("Student");
        pnlProfile.add(lblStud, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 20, -1, -1));

        lblId.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblId.setForeground(new java.awt.Color(0, 0, 204));
        pnlProfile.add(lblId, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 40, -1, -1));

        getContentPane().add(pnlProfile, new org.netbeans.lib.awtextra.AbsoluteConstraints(165, -10, 1120, 70));

        pnlMain.setBackground(new java.awt.Color(255, 255, 255));
        pnlMain.setMinimumSize(new java.awt.Dimension(1075, 640));
        pnlMain.setPreferredSize(new java.awt.Dimension(1075, 650));
        pnlMain.setLayout(new java.awt.CardLayout());
        getContentPane().add(pnlMain, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 60, 1075, 650));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void pnlCheckResultMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlCheckResultMouseClicked

        submit.setVisible(false);
        present.setVisible(false);
        result.setVisible(true);

        lblCheckResult.setForeground(new java.awt.Color(56, 182, 255));

        lblReqPresentation.setForeground(new java.awt.Color(153,153,153));
        lblReportSub.setForeground(new java.awt.Color(153,153,153));

    }//GEN-LAST:event_pnlCheckResultMouseClicked

    private void pnlCheckResultMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlCheckResultMouseEntered
        pnlCheckResult.setBackground(Color.white);
    }//GEN-LAST:event_pnlCheckResultMouseEntered

    private void pnlCheckResultMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlCheckResultMouseExited
        pnlCheckResult.setBackground(new java.awt.Color(15,30,55));
    }//GEN-LAST:event_pnlCheckResultMouseExited

    private void pnlReqPresentationMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlReqPresentationMouseClicked

        submit .setVisible(false);
         present.setVisible(true);
        result.setVisible(false);

        lblReqPresentation.setForeground(new java.awt.Color(56, 182, 255));

        lblReportSub.setForeground(new java.awt.Color(153,153,153));
        lblCheckResult.setForeground(new java.awt.Color(153,153,153));

    }//GEN-LAST:event_pnlReqPresentationMouseClicked

    private void pnlReqPresentationMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlReqPresentationMouseEntered
        pnlReqPresentation.setBackground(Color.white);
    }//GEN-LAST:event_pnlReqPresentationMouseEntered

    private void pnlReqPresentationMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlReqPresentationMouseExited
        pnlReqPresentation.setBackground(new java.awt.Color(15,30,55));
    }//GEN-LAST:event_pnlReqPresentationMouseExited

    private void pnlReportSubMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlReportSubMouseClicked
        pnlReportSub.setBackground(Color.white);
//        dash.setVisible(false);
        submit.setVisible(true);
        present.setVisible(false);
        result.setVisible(false);
//        view.setVisible(false);
//        request.setVisible(false);
        lblReportSub.setForeground(new java.awt.Color(56, 182, 255));

        lblReqPresentation.setForeground(new java.awt.Color(153,153,153));
        lblCheckResult.setForeground(new java.awt.Color(153,153,153));
 
    }//GEN-LAST:event_pnlReportSubMouseClicked

    private void pnlReportSubMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlReportSubMouseEntered
        pnlReportSub.setBackground(Color.white);
    }//GEN-LAST:event_pnlReportSubMouseEntered

    private void pnlReportSubMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlReportSubMouseExited
        pnlReportSub.setBackground(new java.awt.Color(15,30,55));
    }//GEN-LAST:event_pnlReportSubMouseExited

    private void lblMiniMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMiniMouseClicked
        this.setExtendedState(Admin.ICONIFIED);
    }//GEN-LAST:event_lblMiniMouseClicked

    private void lblExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblExitMouseClicked
        System.exit(0);
    }//GEN-LAST:event_lblExitMouseClicked

    private void lblSignOutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSignOutMouseClicked
        LoginPage login = new LoginPage();
        login.show();
        dispose();// closing our current Menu
        JOptionPane.showMessageDialog(null, "Logout successful");
    }//GEN-LAST:event_lblSignOutMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StudentPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblAdminIcon;
    private javax.swing.JLabel lblCheckResult;
    private javax.swing.JLabel lblExit;
    private javax.swing.JLabel lblId;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblMini;
    private javax.swing.JLabel lblReportSub;
    private javax.swing.JLabel lblReqPresentation;
    private javax.swing.JLabel lblSignOut;
    private javax.swing.JLabel lblStud;
    private javax.swing.JPanel pnlCheckResult;
    private javax.swing.JLayeredPane pnlMain;
    private javax.swing.JPanel pnlMenu;
    private javax.swing.JPanel pnlProfile;
    private javax.swing.JPanel pnlReportSub;
    private javax.swing.JPanel pnlReqPresentation;
    // End of variables declaration//GEN-END:variables
}
