/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package system;

import java.awt.Color;
import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;
import java.text.SimpleDateFormat;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.Date;
import javax.swing.border.Border;
import javax.swing.border.LineBorder;

/**
 *
 * @author nisha
 */
public class StudentDashboardA extends javax.swing.JPanel {

    /**
     * Creates new form StudentDashboard
     */
    StudentRegistration studentR = new StudentRegistration();
    CourseList course = new CourseList();
    StudentEditDelete modify = new StudentEditDelete();
    StudentRegistrationList list = new StudentRegistrationList();
    Border lineBorder = new LineBorder(Color.BLUE, 2, true);
    Border lineBorder2 = new LineBorder(Color.WHITE, 2, true);
    
    public StudentDashboardA() {
        initComponents();
        pnlMainDash.add(studentR);
        pnlMainDash.add(course);
        pnlMainDash.add(modify);
        pnlMainDash.add(list);
        studentR.setVisible(false);
        course.setVisible(false);
        modify.setVisible(false);
        list.setVisible(false);
        
        Date currentDate = new Date();
        
        // Create SimpleDateFormat instance with the desired format
        SimpleDateFormat sdf = new SimpleDateFormat("MMMM d, EEEE");
        
        // Format the current date
        String formattedDate = sdf.format(currentDate); 
        lblDate.setText(formattedDate.toString());
        
        // Count records and set label text
        int totalRecords = countRecords();
        lblTotalS.setText(String.valueOf(totalRecords));
       
        
       
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlMainDash = new javax.swing.JLayeredPane();
        pnlDashS = new javax.swing.JPanel();
        lblStudentDTitle = new javax.swing.JLabel();
        lblDate = new javax.swing.JLabel();
        lblSTitle = new javax.swing.JLabel();
        lblMsg = new javax.swing.JLabel();
        lblBgDashS = new javax.swing.JLabel();
        lblModifyS = new javax.swing.JLabel();
        lblCourseS = new javax.swing.JLabel();
        lblListS = new javax.swing.JLabel();
        lblRegS = new javax.swing.JLabel();
        lblManage = new javax.swing.JLabel();
        lblTotalS = new javax.swing.JLabel();
        lblTTotal = new javax.swing.JLabel();
        lblTS = new javax.swing.JLabel();
        lblBgTotal = new javax.swing.JLabel();
        lblBox = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(1075, 650));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlMainDash.setLayout(new java.awt.CardLayout());

        pnlDashS.setBackground(new java.awt.Color(255, 255, 255));
        pnlDashS.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblStudentDTitle.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        lblStudentDTitle.setText("Dashboard Student");
        pnlDashS.add(lblStudentDTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 35, -1, -1));

        lblDate.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblDate.setForeground(new java.awt.Color(255, 255, 255));
        lblDate.setText("jLabel1");
        pnlDashS.add(lblDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 130, 190, -1));

        lblSTitle.setBackground(new java.awt.Color(255, 255, 255));
        lblSTitle.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lblSTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblSTitle.setText("Student Management ");
        pnlDashS.add(lblSTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 160, -1, -1));

        lblMsg.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblMsg.setForeground(new java.awt.Color(255, 255, 255));
        lblMsg.setText("Welcome back, Admin!");
        pnlDashS.add(lblMsg, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 220, -1, -1));

        lblBgDashS.setIcon(new javax.swing.ImageIcon(getClass().getResource("/system/img_icon/bgDash2.png"))); // NOI18N
        pnlDashS.add(lblBgDashS, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 690, 180));

        lblModifyS.setBackground(new java.awt.Color(255, 255, 255));
        lblModifyS.setIcon(new javax.swing.ImageIcon(getClass().getResource("/system/img_icon/bgModify.png"))); // NOI18N
        lblModifyS.setOpaque(true);
        lblModifyS.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblModifySMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblModifySMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblModifySMouseExited(evt);
            }
        });
        pnlDashS.add(lblModifyS, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 340, -1, -1));

        lblCourseS.setBackground(new java.awt.Color(255, 255, 255));
        lblCourseS.setIcon(new javax.swing.ImageIcon(getClass().getResource("/system/img_icon/bgCourse.png"))); // NOI18N
        lblCourseS.setOpaque(true);
        lblCourseS.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCourseSMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblCourseSMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblCourseSMouseExited(evt);
            }
        });
        pnlDashS.add(lblCourseS, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 340, -1, -1));

        lblListS.setBackground(new java.awt.Color(255, 255, 255));
        lblListS.setIcon(new javax.swing.ImageIcon(getClass().getResource("/system/img_icon/bgDList.png"))); // NOI18N
        lblListS.setOpaque(true);
        lblListS.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblListSMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblListSMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblListSMouseExited(evt);
            }
        });
        pnlDashS.add(lblListS, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 340, -1, -1));

        lblRegS.setBackground(new java.awt.Color(255, 255, 255));
        lblRegS.setIcon(new javax.swing.ImageIcon(getClass().getResource("/system/img_icon/bgDRegS2.png"))); // NOI18N
        lblRegS.setOpaque(true);
        lblRegS.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblRegSMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblRegSMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblRegSMouseExited(evt);
            }
        });
        pnlDashS.add(lblRegS, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 340, -1, -1));

        lblManage.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        lblManage.setText("Manage");
        pnlDashS.add(lblManage, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 290, -1, -1));

        lblTotalS.setFont(new java.awt.Font("Segoe UI", 1, 60)); // NOI18N
        lblTotalS.setForeground(new java.awt.Color(255, 255, 255));
        lblTotalS.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTotalS.setText("0");
        pnlDashS.add(lblTotalS, new org.netbeans.lib.awtextra.AbsoluteConstraints(929, 155, 80, -1));

        lblTTotal.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lblTTotal.setForeground(new java.awt.Color(255, 255, 255));
        lblTTotal.setText("Total ");
        pnlDashS.add(lblTTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 130, -1, -1));

        lblTS.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblTS.setForeground(new java.awt.Color(255, 255, 255));
        lblTS.setText("Students");
        pnlDashS.add(lblTS, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 230, -1, -1));

        lblBgTotal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/system/img_icon/bgTotal.png"))); // NOI18N
        pnlDashS.add(lblBgTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 100, 280, 180));

        lblBox.setIcon(new javax.swing.ImageIcon(getClass().getResource("/system/img_icon/TransparentBox2.png"))); // NOI18N
        pnlDashS.add(lblBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1075, 650));

        pnlMainDash.add(pnlDashS, "card2");

        add(pnlMainDash, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1075, 650));
    }// </editor-fold>//GEN-END:initComponents

    private void lblRegSMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblRegSMouseEntered

        lblRegS.setBorder(lineBorder); // Set the border to the label
        
    }//GEN-LAST:event_lblRegSMouseEntered

    private void lblRegSMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblRegSMouseClicked

        studentR.setVisible(true);
        course.setVisible(false);
        pnlDashS.setVisible(false);
        modify.setVisible(false);
        list.setVisible(false);
    }//GEN-LAST:event_lblRegSMouseClicked

    private void lblRegSMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblRegSMouseExited
        lblRegS.setBackground(Color.white);
        lblRegS.setBorder(lineBorder2); // Set the border to the label
    }//GEN-LAST:event_lblRegSMouseExited

    private void lblListSMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblListSMouseEntered

        lblListS.setBorder(lineBorder); // Set the border to the label
    }//GEN-LAST:event_lblListSMouseEntered

    private void lblListSMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblListSMouseExited
        lblListS.setBorder(lineBorder2); // Set the border to the label
    }//GEN-LAST:event_lblListSMouseExited

    private void lblListSMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblListSMouseClicked
        studentR.setVisible(false);
        course.setVisible(false);
        pnlDashS.setVisible(false);
        modify.setVisible(false);
        list.setVisible(true);
    }//GEN-LAST:event_lblListSMouseClicked

    private void lblModifySMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblModifySMouseEntered
        lblModifyS.setBorder(lineBorder); // Set the border to the label
    }//GEN-LAST:event_lblModifySMouseEntered

    private void lblModifySMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblModifySMouseExited
        lblModifyS.setBorder(lineBorder2); // Set the border to the label
    }//GEN-LAST:event_lblModifySMouseExited

    private void lblModifySMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblModifySMouseClicked
        studentR.setVisible(false);
        course.setVisible(false);
        pnlDashS.setVisible(false);
        modify.setVisible(true);
        list.setVisible(false);
    }//GEN-LAST:event_lblModifySMouseClicked

    private void lblCourseSMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCourseSMouseEntered
        lblCourseS.setBorder(lineBorder); // Set the border to the label
    }//GEN-LAST:event_lblCourseSMouseEntered

    private void lblCourseSMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCourseSMouseExited
        lblCourseS.setBorder(lineBorder2); // Set the border to the label
    }//GEN-LAST:event_lblCourseSMouseExited

    private void lblCourseSMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCourseSMouseClicked
        studentR.setVisible(false);
        course.setVisible(true);
        pnlDashS.setVisible(false);
        modify.setVisible(false);
        list.setVisible(false);
    }//GEN-LAST:event_lblCourseSMouseClicked

    //Function for count number of student registered
    public int countRecords() {
    int count = 0;
    try (BufferedReader reader = new BufferedReader(new FileReader("student_list.txt"))) {
        while (reader.readLine() != null) {
            count++;
        }
    } catch (IOException e) {
        e.printStackTrace();
    }
    return count;
}


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblBgDashS;
    private javax.swing.JLabel lblBgTotal;
    private javax.swing.JLabel lblBox;
    private javax.swing.JLabel lblCourseS;
    private javax.swing.JLabel lblDate;
    private javax.swing.JLabel lblListS;
    private javax.swing.JLabel lblManage;
    private javax.swing.JLabel lblModifyS;
    private javax.swing.JLabel lblMsg;
    private javax.swing.JLabel lblRegS;
    private javax.swing.JLabel lblSTitle;
    private javax.swing.JLabel lblStudentDTitle;
    private javax.swing.JLabel lblTS;
    private javax.swing.JLabel lblTTotal;
    private javax.swing.JLabel lblTotalS;
    private javax.swing.JPanel pnlDashS;
    private javax.swing.JLayeredPane pnlMainDash;
    // End of variables declaration//GEN-END:variables
}
